[package]
name = "prisma-query-engine-c-api"
version = "0.1.0"
edition = "2021"
authors = ["Seven Du <whine.whitish.0u@icloud.com>"]
repository = "https://github.com/odroe/prisma"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib"]

[features]
vendored-openssl = ["sql-connector/vendored-openssl"]

[dependencies]
datamodel = { git = "https://github.com/prisma/prisma-engines" }
datamodel-connector = { git = "https://github.com/prisma/prisma-engines" }
query-core = { git = "https://github.com/prisma/prisma-engines" }
query-connector = { git = "https://github.com/prisma/prisma-engines" }
prisma-models = { git = "https://github.com/prisma/prisma-engines" }
request-handlers = { git = "https://github.com/prisma/prisma-engines" }
user-facing-errors = { git = "https://github.com/prisma/prisma-engines" }
sql-connector = { git = "https://github.com/prisma/prisma-engines", package = "sql-query-connector" }

libc = "0.2.132"
thiserror = "1.0.34"
serde = "1.0.144"
serde_json = "1.0.85"
url = "2.3.1"
connection-string = "0.1.14"
tokio = "1.22.0"
futures = "0.3.24"
once_cell = "1.14.0"
intmap = "2.0.0"

[build-dependencies]
cbindgen = "0.24.3"
