name: Build Linux Dynamic Library
on: workflow_call
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
    runs-on: matrix.os
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: build-${{ runner.os }}-${{ matrix.arch }}-dylib-${{ hashFiles('**/Cargo.lock') }}
      - name: 'error: linking with cc failed: exit code: 1 (https://github.com/rust-lang/rust/issues/25289)'
        if: matrix.arch == 'aarch64'
        run: sudo apt install gcc-multilib
      - name: Set rustup target
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu
      - name: Build
        run: cargo build --target ${{ matrix.arch }}-unknown-linux-gnu --release --verbose
      - name: Rename artifact
        run: mv target/${{ matrix.arch }}-unknown-linux-gnu/release/libprisma_query_engine_c_api.so linux-${{ matrix.arch }}.so
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: linux-${{ matrix.arch }}.so