name: Commit Test
on:
  push:
    branches: [ "main" ]
  pull_request:
      paths-ignore:
        - '*.md'
        - LICENSE
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --verbose