name: Commit Test
on:
  push
  pull_request:
      paths-ignore:
        - '*.md'
        - LICENSE
  workflow_call
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: matrix.os
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --verbose