name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  build-c-header:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cbindgen
        run: cargo install cbindgen
      
      - name: Build C header file
        run: cbindgen --config cbindgen.toml --output target/api.h

      - name: Upload `api.h` file
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: ${{ github.workspace }}/target/api.h

  deploy-c-header:
    needs: [build-c-header]
    runs-on: ubuntu-latest
    steps:
      - name: Download `api.h` file
        uses: actions/download-artifact@v2
        with:
          name: assets
          path: ${{ github.workspace }}/assets
        run: ls -al ${{ github.workspace }}/assets
          
